### ISSUE TITLE
Simple quote demo

### ISSUE THREAD

**Issue by paultuckey** [ShowcaseSoftwareLtd/showcase-workshop-apis#1]
@limey has requested a demo for HTML5 zip to do a quote:

Make an HTML5 zip bundle that does the following (use bootstrap and jquery)

  - Listing page - list submitted quotes with a big "New Quote" button at the top
  - New Quote page - simple form
    - name, address, phone number, email address
    - a large textarea for details and price field, submit button
    - When the submit button is tapped call the data-api and save it locally
  - Thanks page with link back to listing page

**Comment by paultuckey** [comment]
cleaning up.

**Comment by vincentaudebert** [comment]
:'( :D
